-- Catálogo de modelos de vehículo eléctrico, del componente Vehículos.
--
-- Nombre del archivo con timestamp, NUNCA V1/V2/V3. Ver README, "Migraciones".
-- Sin calificar el schema: lo pone Flyway (spring.flyway.schemas=core).
--
-- **Es un catálogo cerrado, y esa es la decisión de diseño.** El conductor elige de esta lista
-- en vez de escribir su auto a mano. La diferencia no es de comodidad: el tipo de conector y el
-- tope de carga que salen de acá son los que después filtran estaciones y estiman cuánto tarda
-- una carga. Un texto libre —"tesla model 3", "TESLA M3"— no sirve para comparar contra
-- connectors.connector_type, y una potencia tipeada por el usuario convierte una estimación en
-- una adivinanza. Agregar un modelo es una migración nueva, no un formulario.
--
-- No hay columna de imagen: hay UN solo dibujo de auto en el frontend (public/car.png) y es
-- genérico. Una columna apuntando a archivos que no existen sería peor que no tenerla.

CREATE TABLE vehicle_models (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    brand          VARCHAR(60)  NOT NULL,
    name           VARCHAR(60)  NOT NULL,

    -- El estándar físico que acepta el auto. Mismo vocabulario que
    -- connectors.connector_type, porque la comparación entre los dos es todo el punto del
    -- catálogo. Como allá, se guarda el NOMBRE del enum y no su ordinal.
    connector_type VARCHAR(20)  NOT NULL,

    -- Potencia del motor, en kW. Es el único dato que no entra en ninguna cuenta: va porque es
    -- lo que identifica a una versión frente a otra del mismo modelo.
    motor_kw       NUMERIC(6,2) NOT NULL,

    -- Lo máximo que el auto acepta AL CARGAR, en kW, que no es la potencia del motor ni la del
    -- cargador. Es el dato que vuelve útil al catálogo: en una estación de 180 kW un Leaf
    -- igual carga a 50, así que el surtidor más rápido no siempre le sirve de más.
    max_charge_kw  NUMERIC(6,2) NOT NULL,

    -- Capacidad utilizable de la batería, en kWh. Con max_charge_kw alcanza para estimar una
    -- carga completa.
    battery_kwh    NUMERIC(6,2) NOT NULL,

    -- La baja es lógica, igual que en estaciones y medios de pago: un modelo discontinuado
    -- puede seguir elegido en el perfil de alguien, y borrar la fila dejaría ese perfil
    -- apuntando a la nada.
    active         BOOLEAN      NOT NULL DEFAULT TRUE,

    -- Marca y modelo juntos identifican al auto. Sin esto, dos migraciones que agreguen el
    -- mismo modelo dejan el selector con la entrada repetida y dos ids para la misma ficha.
    CONSTRAINT uq_vehicle_models_brand_name UNIQUE (brand, name)
);

-- El selector se pide entero y ordenado por marca; es la única consulta que hace la pantalla.
CREATE INDEX idx_vehicle_models_active ON vehicle_models (active, brand, name);
