-- Historial de avisos al conductor, del componente Notificaciones (RF17, ECO-41).
--
-- Nombre con timestamp, NUNCA V1/V2/V3. Ver README, "Migraciones".
-- Sin calificar el schema: lo pone Flyway (spring.flyway.schemas=async).

CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- La clave de deduplicación que trae el mensaje. UNIQUE es la garantía de fondo: el
    -- servicio consulta antes de guardar, pero si dos entregas del mismo mensaje llegan a la
    -- vez, las dos pueden consultar y no ver nada. La restricción deja pasar a una sola.
    event_id      VARCHAR(120) NOT NULL UNIQUE,

    -- Conductor destinatario. Sin clave foránea, por el mismo motivo que payment_methods.driver_id:
    -- la tabla de usuarios vive en el schema de ecopedia-core, que es otro artefacto.
    recipient_id  BIGINT       NOT NULL,

    type          VARCHAR(40)  NOT NULL,

    -- El texto ya armado, tal como se mostró y se mandó. Se guarda armado y no se rearma al
    -- leerlo porque un aviso es un registro de lo que se le dijo al conductor: si mañana la
    -- estación cambia de nombre, el aviso de ayer tiene que seguir diciendo lo que dijo.
    title         VARCHAR(120) NOT NULL,
    body          VARCHAR(500) NOT NULL,

    -- Los datos de la reserva, para que la pantalla pueda enlazar al aviso con su reserva.
    booking_id    BIGINT       NOT NULL,
    connector_id  BIGINT       NOT NULL,
    window_start  TIMESTAMP WITH TIME ZONE NOT NULL,
    window_end    TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Lo que se le preguntó a core al recibir el mensaje. Nulos si core no contestó: el aviso
    -- se guarda igual, con el texto armado sin el nombre de la estación.
    station_id    BIGINT,
    station_name  VARCHAR(200),

    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Cuándo lo leyó el conductor. Nulo mientras no lo haya leído.
    read_at       TIMESTAMP WITH TIME ZONE
);

-- Toda consulta de la pantalla arranca por "los avisos de este conductor, los más nuevos primero".
CREATE INDEX idx_notifications_recipient ON notifications (recipient_id, created_at);
